### ISSUE TITLE
oursql should not be part of requirement

### ISSUE THREAD

**Issue by wenzong** [juwai/zask#3]
since we already using SQLAlchemy, using specific driver should be application's decision

**Comment by stuartwan** [comment]
What are the (recommended) alternatives?

**Comment by stuartwan** [comment]
I saw SqlAlchemy supports below DBAPI:
- MySQL-Python
- PyMySQL
- MySQL Connector/Python
- CyMySQL
- OurSQL
- Google Cloud SQL
- PyODBC
- zxjdbc for Jython

**Comment by wenzong** [comment]
@imlazyone this should be application developer's choice

however, personally I prefer pure Python implement, PyMySQL should be a good one

**Comment by liangshan** [comment]
PyMySQL +1， lasted `mysql-client` is better than `oursql`
